import { Video, User } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'user1',
    name: 'Alex Rivers',
    email: 'alex@example.com',
    photoURL: 'https://picsum.photos/seed/alex/200/200',
    bio: 'Digital nomad and tech enthusiast.',
    followers: ['user2'],
    following: ['user2'],
    createdAt: Date.now(),
  },
  {
    id: 'user2',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    photoURL: 'https://picsum.photos/seed/sarah/200/200',
    bio: 'Travel blogger and foodie.',
    followers: ['user1'],
    following: ['user1'],
    createdAt: Date.now(),
  },
];

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'vid1',
    title: 'Exploring the Swiss Alps',
    description: 'A beautiful journey through the mountains of Switzerland.',
    thumbnailUrl: 'https://picsum.photos/seed/alps/1280/720',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    authorId: 'user1',
    authorName: 'Alex Rivers',
    authorPhoto: 'https://picsum.photos/seed/alex/200/200',
    views: 12500,
    likes: ['user2'],
    commentsCount: 45,
    category: 'Travel',
    type: 'long',
    tags: ['travel', 'nature', 'alps'],
    createdAt: Date.now() - 86400000,
    duration: 596,
  },
  {
    id: 'vid2',
    title: 'Morning Coffee Routine',
    description: 'How I start my day.',
    thumbnailUrl: 'https://picsum.photos/seed/coffee/720/1280',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    authorId: 'user2',
    authorName: 'Sarah Chen',
    authorPhoto: 'https://picsum.photos/seed/sarah/200/200',
    views: 45000,
    likes: ['user1'],
    commentsCount: 120,
    category: 'Cooking',
    type: 'short',
    tags: ['lifestyle', 'coffee', 'morning'],
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'vid3',
    title: 'Tech Review: New Laptop',
    description: 'Is it worth the hype?',
    thumbnailUrl: 'https://picsum.photos/seed/laptop/1280/720',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    authorId: 'user1',
    authorName: 'Alex Rivers',
    authorPhoto: 'https://picsum.photos/seed/alex/200/200',
    views: 8900,
    likes: [],
    commentsCount: 12,
    category: 'Tech',
    type: 'long',
    tags: ['tech', 'review', 'laptop'],
    createdAt: Date.now() - 172800000,
    duration: 420,
  },
  {
    id: 'vid4',
    title: 'Quick Pasta Recipe',
    description: 'Dinner in 10 minutes.',
    thumbnailUrl: 'https://picsum.photos/seed/pasta/720/1280',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    authorId: 'user2',
    authorName: 'Sarah Chen',
    authorPhoto: 'https://picsum.photos/seed/sarah/200/200',
    views: 120000,
    likes: ['user1'],
    commentsCount: 340,
    category: 'Cooking',
    type: 'short',
    tags: ['cooking', 'pasta', 'quick'],
    createdAt: Date.now() - 43200000,
  },
];
